
#first function to be run with pairs analysis. 
#Input data must be a table (tsv, csv, etc.) of genotypes, colnames must be clone names, 
# matrix must be non-ragged (missing values padded with NAs)

#Ex. 
#   clone1name  clone2name  clone3name ...
#   genex       geney       genez
#   geney       genex       genez
# stringsAsFactors=FALSE!! 

#When importing datasets stringsAsFactors=FALSE!! 
 
#function requires Generate_Pairs_Dataframe to be sourced 
#matrixStats must be loaded before plyr 

Construct_Pairs = function(Genes_by_clone_dataframe) {
  #library(plyr)
  
  #first set up an empty dataframe

  all.data = data.frame(matrix(vector(), 0, 2,
                        dimnames=list(c(), c("X1", "X2"))),
                        stringsAsFactors=F)
  #count all how many times each gene appears
  all.genes<-list() #loop will fill all.genes with all genes in dataset
  for (h in names(Genes_by_clone_dataframe)){
    list<-na.omit(Genes_by_clone_dataframe[, h], stringsAsFactors=FALSE) 
    all.genes<-append(all.genes, list)
  } 
  df<-data.frame(matrix(unlist(all.genes),nrow=length(all.genes), byrow=T), stringsAsFactors=FALSE)
  colnames(df)[1]<- "sigma2"
  gene_counts.2<-count(df, "sigma2")
  M<- sum(gene_counts.2[, 2])
  epsilon<-1/M
  N<- ncol(Genes_by_clone_dataframe)
  rm(df, all.genes)
  Genes_by_clone_dataframe-> x
 
  for(i in names(Genes_by_clone_dataframe)){
    #combn() generates all pairwise combinations
    list<-na.omit(Genes_by_clone_dataframe[, i])
    generatepairs<-combn(list, 2, simplify=FALSE, stringsAsFactors=FALSE)
    # convert the string generated by combn() to a dataframe 
    #with the 2 columns being the two genes in the pair
    pairs.to.df <-data.frame(matrix(unlist(generatepairs),nrow=length(generatepairs), byrow=T), stringsAsFactors=FALSE)
    all.data<-rbind(all.data, pairs.to.df, stringsAsFactors=FALSE)
  }
  
  All.Pairs<-Generate_Pairs_Dataframe(Genes_by_clone_dataframe)
 ##sig1countdf will store sigma1 frequencies for later  
  sig1countdf<- All.Pairs[1:2]
  gene_counts.1<-gene_counts.2
  colnames(gene_counts.1)[1]<- "sigma1"
  sig1countdf<- merge(sig1countdf, gene_counts.1, by="sigma1")
  colnames(sig1countdf)[3]<-"sigma1.count"
  sig1countdf<-sig1countdf[2:3]

  ## take the above dataframe and add a column that 
  #contains both gene names using paste()
  # then use cbind() to add the new column to the dataframe
  sigma1.sigma2<- paste(pmin(all.data$X1, all.data$X2), pmax(all.data$X1, all.data$X2))
  ## old way without alphebetizing
  all.data<-cbind(sigma1.sigma2, all.data)
  pairscount<-count(all.data, "sigma1.sigma2") 
  # merge by pairs
  All.Pairs<-merge(All.Pairs, pairscount, by="sigma1.sigma2", all=TRUE) 
  # ## rename the column
  colnames(All.Pairs)[4]<-"Observed_sigma1.sigma2_Frequncy" 
  All.Pairs<-merge(All.Pairs, gene_counts.2, by="sigma2", all=TRUE) #col 5 is sigma 2 freq
  colnames(All.Pairs)[5]<-"sigma2_Observed_Frequency"
 
  All.Pairs<-All.Pairs[, c(1, 5, 2, 4)]
  All.Pairs[is.na(All.Pairs)]<-0
  #replace na values for non-occuring pairs with 0
  All.Pairs<- All.Pairs[All.Pairs$sigma1.sigma2!= "FALSE FALSE", ]
  All.Pairs<-merge(All.Pairs, sig1countdf, by="sigma1.sigma2")

  All.Pairs<-All.Pairs[, c(2,3,1,4,5)]  
  C0<- 1/(N*(1+epsilon))
  C <- 1/(N*(1+epsilon)^2)
  Msig1<- (All.Pairs[,5] + (N*epsilon))
  Msig2<- (All.Pairs[,2] + (N*epsilon))
  Po1<- Msig1 * C0
  Po2<- Msig2 * C0 
  Clones0.0<- N - ((All.Pairs[, 2]+ All.Pairs[, 5])-All.Pairs[, 4])
 
  All.Pairs$"Po1,o2(1,1)"<- C* ((((1+epsilon)^2)*All.Pairs[,4]) + 
                                (((1+epsilon)*epsilon)* ((All.Pairs[,2]-All.Pairs[,4]) + (All.Pairs[,5]-All.Pairs[,4]))) +
                                ((epsilon^2)*Clones0.0))
 
  All.Pairs$"Po1,o2(0,1)"<- C* ((All.Pairs[,2]-All.Pairs[,4])+((All.Pairs[,2]-All.Pairs[,4])*epsilon)+(Clones0.0*epsilon))
  All.Pairs$"Po1,o2(1,0)"<- C* ((All.Pairs[,5]-All.Pairs[,4])+((All.Pairs[,5]-All.Pairs[,4])*epsilon)+(Clones0.0*epsilon))
  All.Pairs$"Po1,o2(0,0)"<- C * Clones0.0
  All.Pairs$"Po1"<- Po1
  All.Pairs$"Po2"<- Po2
  All.Pairs<- All.Pairs[c(3,4,1,2,6,7,8,9,10,11)]
 P1.1<- All.Pairs[, 5]
 P0.1<- All.Pairs[, 6]
 P1.0<- All.Pairs[, 7]
 P0.0<- All.Pairs[, 8]
 Psig1<- All.Pairs[, 9]
 Psig2<- All.Pairs[, 10]
 I1.1<- P1.1 * log2(P1.1/(Psig1*Psig2))
 I0.1<- P0.1 * log2(P0.1/((1-Psig1)*Psig2))
 I1.0<- P1.0 * log2(P1.0/(Psig1 *(1-Psig2)))
 I0.0<- P0.0 * log2(P0.0/((1-Psig1)*(1-Psig2)))
 I.df<- data.frame(All.Pairs[1], I1.1, I0.1, I1.0, I0.0)
 I.df$I<- (rowSums(I.df[2:5]))
 I.df<-I.df[c(1, 6)]
 colnames(I.df)[2]<- "Observed  MI"
  return(I.df)
}